CREATE TABLE TapahtumanLuoja
(
id INT NOT NULL AUTO_INCREMENT,
etunimi VARCHAR (45) NOT NULL,
sukunimi VARCHAR (45) NOT NULL,
email VARCHAR (45) NOT NULL,
PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Teema
(
teemaId INT NOT NULL AUTO_INCREMENT,
nimi VARCHAR (45) NOT NULL,
PRIMARY KEY(teemaId)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Paikkakunta
(
paikkaId INT NOT NULL AUTO_INCREMENT,
nimi VARCHAR (45) NOT NULL,
PRIMARY KEY(paikkaId)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Tapahtuma
(
TapId INT NOT NULL AUTO_INCREMENT,
TapLuojaId INT NOT NULL AUTO_INCREMENT,
teema INT NOT NULL AUTO_INCREMENT,
paikka VARCHAR (45) NOT NULL,
TapNimi VARCHAR (100) NOT NULL,
pvm DATE NOT NULL,
aika CHAR (5) NOT NULL,
paikkakunta INT NOT NULL,
lisatiedot VARCHAR (60),
PRIMARY KEY(TapId),
FOREIGN KEY(TapLuojaId) REFERENCES TapahtumanLuoja(id),
FOREIGN KEY(teema) REFERENCES Teema(teemaId),
FOREIGN KEY(paikkakunta) REFERENCES Paikkakunta(paikkaId),
)ENGINE=InnoDB DEFAULT CHARSET=utf8;